ide:
    build: .
    ports:
        - 80:80
        - 9999:8080
    volumes:
        - ~/c9_workspace:/workspace
        #- /var/log/httpd:/logs:ro
    command: /usr/bin/supervisord -c /etc/supervisord.conf
